# Generated by Django 4.2.19 on 2025-02-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredface',
            name='embedding',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeredface',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
